language: ruby
rvm:
- 2.2.2
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: 07sZ1wKIU2NjIKWyv3utMzhH7UseK9dDijTC2QRqhFEKLWo8e3FtkadPRf/g+u9XiiN1s7fjiy68M5Ill7Ostuu2lQqhTTfiQlJFIN4j80kD96WzjTnAxbZ9ReqkZ2XFz35lZVhDVfsCwp9V9dDO9/Qj+tuHqthGKEvqCjaWHoSztsvX/wDu+RI4FzqgqCMAmRCMUwWSQOkGhlv9rXkDWc3oMRhMjYEXhH7mkEoRCOIodB7/vI6znLM+tPcr+/gUwLvNjqsAm8EpPHsyOuF0DtXM1D+NYkSa9owmOjz2mizbqq9M6XTWu0Hk0Xv8y9tNLnVKYdiuT4OJbgIkvK4ZRTnIiID+Z3eIKo7tB0lZXtJ6NijrXzlFWOqMAaghgktuknkpmd26ckulP7B9QDO4b0BtMHjm5IB4EUE09MSbrZsts005AEyHsV7H29kCbpOJ4Mq6zcjClimNmrCn6gtHPM4IPlxs6LkDrES+Fc/+iMFgSAU1krPNAmXTYgcttYWTon1u0Vq0+M2tH0oQ7hDhf0iocYZbAIy+77rQw0KeCmlT9ponwe1/qbAA71umj0ZOzzFwfOdh/LIzjfTq+8AP2pneVQUkiEmA8EzjYA1US9ZnUmJ2eHa+Gj4YigjvTwI5r7mrPzmWs5MkFfvLNWVTVu1zNvyYYAuqOL2QOqoRgMw=
  app: sleepy-dawn-4991
  on:
    repo: tiy-hou-q3-2015-rails/week-5-lab-prep
